# cluster.yaml
# kind create cluster --config cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ha-cluster
nodes:
  # Control Plane Nodes
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: control-plane
  - role: control-plane

  # Worker Nodes
  - role: worker
  - role: worker
  - role: worker

networking:
  # Configuração de rede do cluster
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
