#!/bin/bash

# Path
export PATH=$PATH:/usr/sbin
# Set PS1
export PS1="\[\e[31m\][\[\e[m\]\[\e[38;5;172m\]\u\[\e[m\]@\[\e[38;5;153m\]\h\[\e[m\] \[\e[38;5;214m\]\W\[\e[m\]\[\e[31m\]]\[\e[m\]\\$"

# Set timezone
sudo timedatectl set-timezone America/Sao_Paulo